language: node_js

node_js:
  - "8"

branches:
  only:
    - master

services: 
  - postgresql

env:
  - TEST_DB_NAME=cats_test DB_PORT=5432

before_script:
  - psql -c 'create database cats_test;' -U postgres

script: npm install && npm test && cd client && npm install && npm run cy:run